[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn -w 1 -k uvicorn.workers.UvicornWorker backend.synapse_brain:app --timeout 120 --graceful-timeout 30"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
